version: "3.7"
services:
  spark-master:
    image: spark-master:2.3.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8082:8080"
      - "7077:7077"
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
      - /mnt/spark-apps:/opt/spark-apps
      - /mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
#  spark-worker-1:
#    image: spark-worker:2.3.1
#    container_name: spark-worker-1
#    hostname: spark-worker-1
#    depends_on:
#      - spark-master
#    ports:
#      - "8081:8081"
#    env_file: ./env/spark-worker.sh
#    environment:
#      - "SPARK_LOCAL_IP=spark-worker-1"
#    networks:
#      spark-network:
#        ipv4_address: 10.5.0.3
#    volumes:
#      - /mnt/spark-apps:/opt/spark-apps
#      - /mnt/spark-data:/opt/spark-data
#  spark-driver:
#    image: spark-driver:2.3.1
#    container_name: spark-driver1
#    hostname: spark-driver
#    stdin_open: true
#    tty: true
#    ports:
#      - 0.0.0.0:8000:8000
#    networks:
#      spark-network:
#        ipv4_address: 10.5.0.4
#  spark-driver-spring:
#    image: spark-driver-spring:2.3.1
#    container_name: spark-driver-spring
#    hostname: spark-driver-spring
#    stdin_open: true
#    tty: true
#    ports:
#      - 0.0.0.0:3001:3001
#    networks:
#      spark-network:
#        ipv4_address: 10.5.0.7
#  elasticsearch:
#    image: elasticsearch:7.2.0
#    container_name: elasticsearch
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.type=single-node"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - /mnt/test:/usr/share/elasticsearch/datasudo snap rmove
#    ports:
#      - 9200:9200
#      - 9300:9300
#    networks:
#      spark-network:
#        ipv4_address: 10.5.0.5
  kibana:
    image: kibana:7.2.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      spark-network:
        ipv4_address: 10.5.0.6
#  spark-worker-2:
#    image: spark-worker:2.3.1
#    container_name: spark-worker-2
#    hostname: spark-worker-2
#    depends_on:
#      - spark-master
#    ports:
#      - "8082:8081"
#    env_file: ./env/spark-worker.sh
#    environment:
#      - "SPARK_LOCAL_IP=spark-worker-2"
#    networks:
#      spark-network:
#        ipv4_address: 10.5.0.4
#    volumes:
#       - /mnt/spark-apps:/opt/spark-apps
#       - /mnt/spark-data:/opt/spark-data
#  spark-worker-3:
#    image: spark-worker:2.3.1
#    container_name: spark-worker-3
#    hostname: spark-worker-3
#    depends_on:
#      - spark-master
#    ports:
#      - "8083:8081"
#    env_file: ./env/spark-worker.sh
#    environment:
#      - "SPARK_LOCAL_IP=spark-worker-3"
#    networks:
#      spark-network:
#        ipv4_address: 10.5.0.5
#    volumes:
#       - /mnt/spark-apps:/opt/spark-apps
#       - /mnt/spark-data:/opt/spark-data
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16